seed: 0
data:
  preproc_data_path_train: data/preprocessed/human_dataset_v2_tiny/train
  preproc_data_path_eval: data/preprocessed/human_dataset_v2_tiny/val
  preproc_data_path_test: data/preprocessed/human_dataset_v2_tiny/test
  eigenfunctions_path: data/shape_descriptors/human_hks_352.npy
  mesh_path: data/human/RUST_3d_Low1.obj
  img_height: 512
  img_width: 512
  # Images which are completely rendered after the evaluation step (not part of the training dataset)
  eval_render_input_paths:
      - data/human_dataset_v2_tiny/human_vis000
      - data/human_dataset_v2_tiny/human_vis001
      - data/human_dataset_v2_tiny/human_vis002
      - data/human_dataset_v2_tiny/human_vis003
      - data/human_dataset_v2_tiny/human_vis004
  eval_render_img_names:
      - human_vis000
      - human_vis001
      - human_vis002
      - human_vis003
      - human_vis004
model:
  k: 352
  num_layers: 6
  mlp_hidden_dim: 128
  skip_layer_idx: 3
training:
  out_dir: out/shape_descriptors/human_hks
  batch_size: 4096
  lr: 0.0001
  loss_type: L1
  render_every: 5
  print_every: 5
  epochs: 1000
  checkpoint_every: 5
